Repository qazwsx92284/Hacktoberfest_2021, pull requests merged in 2021-10, with the labels that each got.

#2 spring boot project with MySql
  Java/spring-boot-REST-demo-teacher-course/HELP.md
  Java/spring-boot-REST-demo-teacher-course/demo.iml
  Java/spring-boot-REST-demo-teacher-course/mvnw
  Java/spring-boot-REST-demo-teacher-course/mvnw.cmd
  Java/spring-boot-REST-demo-teacher-course/pom.xml
  Java/spring-boot-REST-demo-teacher-course/src/main/java/com/example/demo/ClassDemoApplication.java
  Java/spring-boot-REST-demo-teacher-course/src/main/java/com/example/demo/controllers/CourseController.java
  Java/spring-boot-REST-demo-teacher-course/src/main/java/com/example/demo/controllers/TeacherController.java
  Java/spring-boot-REST-demo-teacher-course/src/main/java/com/example/demo/models/Course.java
  Java/spring-boot-REST-demo-teacher-course/src/main/java/com/example/demo/models/Teacher.java
  Java/spring-boot-REST-demo-teacher-course/src/main/java/com/example/demo/repositories/CourseRepository.java
  Java/spring-boot-REST-demo-teacher-course/src/main/java/com/example/demo/repositories/TeacherRepository.java
  Java/spring-boot-REST-demo-teacher-course/src/main/resources/application.properties
  Java/spring-boot-REST-demo-teacher-course/src/test/java/com/example/demo/ClassDemoApplicationTests.java
  Java/spring-boot-REST-demo-teacher-course/src/test/java/com/example/demo/controllers/CourseControllerTest.java
  Java/spring-boot-REST-demo-teacher-course/target/classes/application.properties
  Java/spring-boot-REST-demo-teacher-course/target/classes/com/example/demo/ClassDemoApplication.class
  Java/spring-boot-REST-demo-teacher-course/target/classes/com/example/demo/controllers/CourseController.class
  Java/spring-boot-REST-demo-teacher-course/target/classes/com/example/demo/controllers/TeacherController.class
  Java/spring-boot-REST-demo-teacher-course/target/classes/com/example/demo/models/Course.class
  Java/spring-boot-REST-demo-teacher-course/target/classes/com/example/demo/models/Teacher.class
  Java/spring-boot-REST-demo-teacher-course/target/classes/com/example/demo/repositories/CourseRepository.class
  Java/spring-boot-REST-demo-teacher-course/target/classes/com/example/demo/repositories/TeacherRepository.class
  Java/spring-boot-REST-demo-teacher-course/target/test-classes/com/example/demo/ClassDemoApplicationTests.class
  Java/spring-boot-REST-demo-teacher-course/target/test-classes/com/example/demo/controllers/CourseControllerTest.class
Labels: hacktoberfest-accepted

#3 Add files via upload
  Java/Mobile_Phone/Mobile_Phone.iml
  Java/Mobile_Phone/pom.xml
  Java/Mobile_Phone/src/main/java/Contact.java
  Java/Mobile_Phone/src/main/java/Main.java
  Java/Mobile_Phone/src/main/java/MobilePhone.java
  Java/Mobile_Phone/src/test/java/MobilePhoneTest.java
  Java/Mobile_Phone/target/classes/Contact.class
  Java/Mobile_Phone/target/classes/Main.class
  Java/Mobile_Phone/target/classes/MobilePhone.class
  Java/Mobile_Phone/target/test-classes/MobilePhoneTest.class
Labels: hacktoberfest-accepted

#4 Create banner.txt
  Java/spring-boot-REST-demo-teacher-course/src/main/resources/banner.txt
Labels: documentation, hacktoberfest-accepted

#6 Spring boot swagger example
  swaggerExample/HELP.md
  swaggerExample/mvnw
  swaggerExample/mvnw.cmd
  swaggerExample/pom.xml
  swaggerExample/src/main/java/com/my/swaggerExample/SwaggerExampleApplication.java
  swaggerExample/src/main/java/com/my/swaggerExample/config/ErrorResponse.java
  swaggerExample/src/main/java/com/my/swaggerExample/config/SwaggerConfig.java
  swaggerExample/src/main/java/com/my/swaggerExample/controller/EmployeeProfileController.java
  swaggerExample/src/main/java/com/my/swaggerExample/model/Employee.java
  swaggerExample/src/main/resources/application.properties
  swaggerExample/src/test/java/com/my/swaggerExample/SwaggerExampleApplicationTests.java
  swaggerExample/swaggerExample.iml
  swaggerExample/target/classes/application.properties
  swaggerExample/target/classes/com/my/swaggerExample/SwaggerExampleApplication.class
  swaggerExample/target/classes/com/my/swaggerExample/config/ErrorResponse.class
  swaggerExample/target/classes/com/my/swaggerExample/config/SwaggerConfig.class
  swaggerExample/target/classes/com/my/swaggerExample/controller/EmployeeProfileController.class
  swaggerExample/target/classes/com/my/swaggerExample/model/Employee.class
  swaggerExample/target/test-classes/com/my/swaggerExample/SwaggerExampleApplicationTests.class
Labels: hacktoberfest-accepted

#7 Java code Searching And Sorting Algo
  Java/Searching/BinarySearch.java
  Java/Searching/BinarySearch1.java
  Java/Searching/LinearSearch.java
  Java/Sorting/BubbleSortMain.java
  Java/Sorting/InsertionSortMain.java
Labels: hacktoberfest-accepted, DSA

#8 Spring Boot REST with volatile db, test collection
  Java/REST_employee_example/HELP.md
  Java/REST_employee_example/bin/HELP.md
  Java/REST_employee_example/bin/mvnw
  Java/REST_employee_example/bin/mvnw.cmd
  Java/REST_employee_example/bin/pom.xml
  Java/REST_employee_example/bin/src/main/java/com/myleec/RestEmployeeExampleApplication.class
  Java/REST_employee_example/bin/src/main/resources/application.properties
  Java/REST_employee_example/bin/src/test/java/com/myleec/RestEmployeeExampleApplicationTests.class
  Java/REST_employee_example/mvnw
  Java/REST_employee_example/mvnw.cmd
  Java/REST_employee_example/pom.xml
  Java/REST_employee_example/src/main/java/com/myleec/RestEmployeeExampleApplication.java
  Java/REST_employee_example/src/main/java/com/myleec/controllers/EmployeeController.java
  Java/REST_employee_example/src/main/java/com/myleec/models/Employee.java
  Java/REST_employee_example/src/main/java/com/myleec/services/EmployeeService.java
  Java/REST_employee_example/src/main/resources/application.properties
  Java/REST_employee_example/src/test/java/com/myleec/RestEmployeeExampleApplicationTests.java
  Java/REST_employee_example/target/classes/application.properties
  Java/REST_employee_example/target/classes/com/myleec/RestEmployeeExampleApplication.class
  Java/REST_employee_example/target/classes/com/myleec/controllers/EmployeeController.class
  Java/REST_employee_example/target/classes/com/myleec/models/Employee.class
  Java/REST_employee_example/target/classes/com/myleec/services/EmployeeService.class
  Java/REST_employee_example/target/test-classes/com/myleec/RestEmployeeExampleApplicationTests.class
  Java/Spring Employee collection.postman_collection.json
Labels: hacktoberfest-accepted
